"""empty message

Revision ID: 0beaa0f88b01
Revises: ecef67e29db3
Create Date: 2022-08-16 04:29:49.506528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beaa0f88b01'
down_revision = 'ecef67e29db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dance', sa.Column('posted_date', sa.Date(), nullable=True))
    op.add_column('dance', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dance', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dance', type_='foreignkey')
    op.drop_column('dance', 'user_id')
    op.drop_column('dance', 'posted_date')
    # ### end Alembic commands ###
